name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: spack/centos7

    steps:
    - uses: actions/checkout@v2
    - name: Generate Dockerfile
      run: spack containerize >Dockerfile
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag foo
